env:
  browser: true
  es6: true
  mocha: true
extends:
  - airbnb-base
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  "import/extensions":
    - error
    - never
  "import/no-unresolved": off
  "import/no-extraneous-dependencies": off
